logout:
    path: /logout
product:
    path:     /product
    controller: App\Controller\DefaultController::indexProduct
show:
    path:     /product/show/{id}
    controller: App\Controller\DefaultController::showProduct